export type Upazila = {
  id: string;
  district_id: string;
  name: string;
  bn_name: string;
  zip_code?: string;
};

const upazilas: Upazila[] = [
  {
    id: "0",
    district_id: "0",
    name: "Debidwar",
    bn_name: "দেবিদ্বার",
    zip_code: "3512",
  },
  {
    id: "1",
    district_id: "0",
    name: "Barura",
    bn_name: "বরুড়া",
    zip_code: "3510",
  },
  {
    id: "2",
    district_id: "0",
    name: "Brahmanpara",
    bn_name: "ব্রাহ্মণপাড়া",
    zip_code: "3502",
  },
  {
    id: "3",
    district_id: "0",
    name: "Chandina",
    bn_name: "চান্দিনা",
    zip_code: "3530",
  },
  {
    id: "4",
    district_id: "0",
    name: "Chauddagram",
    bn_name: "চৌদ্দগ্রাম",
    zip_code: "3550",
  },
  {
    id: "5",
    district_id: "0",
    name: "Daudkandi",
    bn_name: "দাউদকান্দি",
    zip_code: "3516",
  },
  {
    id: "6",
    district_id: "0",
    name: "Homna",
    bn_name: "হোমনা",
    zip_code: "3540",
  },
  {
    id: "7",
    district_id: "0",
    name: "Laksam",
    bn_name: "লাকসাম",
    zip_code: "3570",
  },
  {
    id: "8",
    district_id: "0",
    name: "Muradnagar",
    bn_name: "মুরাদনগর",
    zip_code: "3580",
  },
  {
    id: "9",
    district_id: "0",
    name: "Nangalkot",
    bn_name: "নাঙ্গলকোট",
    zip_code: "3590",
  },
  {
    id: "10",
    district_id: "0",
    name: "Cumilla Sadar",
    bn_name: "কুমিল্লা সদর",
    zip_code: "3520",
  },
  {
    id: "11",
    district_id: "0",
    name: "Meghna",
    bn_name: "মেঘনা",
    zip_code: "3515",
  },
  {
    id: "12",
    district_id: "0",
    name: "Monohargonj",
    bn_name: "মনোহরগঞ্জ",
    zip_code: "3560",
  },
  {
    id: "13",
    district_id: "0",
    name: "Cumilla Sadar Dakshin",
    bn_name: "কুমিল্লা সদর দক্ষিণ",
    zip_code: "3500",
  },
  {
    id: "14",
    district_id: "0",
    name: "Titas",
    bn_name: "তিতাস",
    zip_code: "3525",
  },
  {
    id: "15",
    district_id: "0",
    name: "Burichang",
    bn_name: "বুড়িচং",
    zip_code: "3520",
  },
  {
    id: "16",
    district_id: "0",
    name: "Lalmai",
    bn_name: "লালমাই",
    zip_code: "3506",
  },
  {
    id: "17",
    district_id: "1",
    name: "Chhagalnaiya",
    bn_name: "ছাগলনাইয়া",
    zip_code: "3910",
  },
  {
    id: "18",
    district_id: "1",
    name: "Feni Sadar",
    bn_name: "ফেনী সদর",
    zip_code: "3900",
  },
  {
    id: "19",
    district_id: "1",
    name: "Sonagazi",
    bn_name: "সোনাগাজী",
    zip_code: "3950",
  },
  {
    id: "20",
    district_id: "1",
    name: "Fulgazi",
    bn_name: "ফুলগাজী",
    zip_code: "3930",
  },
  {
    id: "21",
    district_id: "1",
    name: "Parshuram",
    bn_name: "পরশুরাম",
    zip_code: "3920",
  },
  {
    id: "22",
    district_id: "1",
    name: "Daganbhuiyan",
    bn_name: "দাগনভূঞা",
    zip_code: "3940",
  },
  {
    id: "23",
    district_id: "2",
    name: "Brahmanbaria Sadar",
    bn_name: "ব্রাহ্মণবাড়িয়া সদর",
    zip_code: "3400",
  },
  {
    id: "24",
    district_id: "2",
    name: "Kasba",
    bn_name: "কসবা",
    zip_code: "3460",
  },
  {
    id: "25",
    district_id: "2",
    name: "Nasirnagar",
    bn_name: "নাসিরনগর",
    zip_code: "3440",
  },
  {
    id: "26",
    district_id: "2",
    name: "Sarail",
    bn_name: "সরাইল",
    zip_code: "3470",
  },
  {
    id: "27",
    district_id: "2",
    name: "Ashuganj",
    bn_name: "আশুগঞ্জ",
    zip_code: "3402",
  },
  {
    id: "28",
    district_id: "2",
    name: "Akhaura",
    bn_name: "আখাউড়া",
    zip_code: "3450",
  },
  {
    id: "29",
    district_id: "2",
    name: "Nabinagar",
    bn_name: "নবীনগর",
    zip_code: "3410",
  },
  {
    id: "30",
    district_id: "2",
    name: "Bancharampur",
    bn_name: "বাঞ্ছারামপুর",
    zip_code: "3420",
  },
  {
    id: "31",
    district_id: "2",
    name: "Bijoynagar",
    bn_name: "বিজয়নগর",
    zip_code: "3430",
  },
  {
    id: "32",
    district_id: "3",
    name: "Rangamati Sadar",
    bn_name: "রাঙ্গামাটি সদর",
    zip_code: "4500",
  },
  {
    id: "33",
    district_id: "3",
    name: "Kaptai",
    bn_name: "কাপ্তাই",
    zip_code: "4530",
  },
  {
    id: "34",
    district_id: "3",
    name: "Kawkhali",
    bn_name: "কাউখালী",
    zip_code: "4540",
  },
  {
    id: "35",
    district_id: "3",
    name: "Baghaichari",
    bn_name: "বাঘাইছড়ি",
    zip_code: "4570",
  },
  {
    id: "36",
    district_id: "3",
    name: "Barkal",
    bn_name: "বরকল",
    zip_code: "4520",
  },
  {
    id: "37",
    district_id: "3",
    name: "Langadu",
    bn_name: "লংগদু",
    zip_code: "4550",
  },
  {
    id: "38",
    district_id: "3",
    name: "Rajasthali",
    bn_name: "রাজস্থলী",
    zip_code: "4590",
  },
  {
    id: "39",
    district_id: "3",
    name: "Belaichari",
    bn_name: "বিলাইছড়ি",
    zip_code: "4560",
  },
  {
    id: "40",
    district_id: "3",
    name: "Juraichari",
    bn_name: "জুরাছড়ি",
    zip_code: "4580",
  },
  {
    id: "41",
    district_id: "3",
    name: "Naniarchar",
    bn_name: "নানিয়ারচর",
    zip_code: "4510",
  },
  {
    id: "42",
    district_id: "4",
    name: "Noakhali Sadar",
    bn_name: "নোয়াখালী সদর",
    zip_code: "3800",
  },
  {
    id: "43",
    district_id: "4",
    name: "Companiganj",
    bn_name: "কোম্পানীগঞ্জ",
    zip_code: "3840",
  },
  {
    id: "44",
    district_id: "4",
    name: "Begumganj",
    bn_name: "বেগমগঞ্জ",
    zip_code: "3820",
  },
  {
    id: "45",
    district_id: "4",
    name: "Hatia",
    bn_name: "হাতিয়া",
    zip_code: "3890",
  },
  {
    id: "46",
    district_id: "4",
    name: "Subarnachar",
    bn_name: "সুবর্ণচর",
    zip_code: "3880",
  },
  {
    id: "47",
    district_id: "4",
    name: "Kabirhat",
    bn_name: "কবিরহাট",
    zip_code: "3850",
  },
  {
    id: "48",
    district_id: "4",
    name: "Senbug",
    bn_name: "সেনবাগ",
    zip_code: "3860",
  },
  {
    id: "49",
    district_id: "4",
    name: "Chatkhil",
    bn_name: "চাটখিল",
    zip_code: "3830",
  },
  {
    id: "50",
    district_id: "4",
    name: "Sonaimori",
    bn_name: "সোনাইমুড়ী",
    zip_code: "3870",
  },
  {
    id: "51",
    district_id: "5",
    name: "Haimchar",
    bn_name: "হাইমচর",
    zip_code: "3660",
  },
  {
    id: "52",
    district_id: "5",
    name: "Kachua",
    bn_name: "কচুয়া",
    zip_code: "3630",
  },
  {
    id: "53",
    district_id: "5",
    name: "Shahrasti",
    bn_name: "শাহরাস্তি	",
    zip_code: "3670",
  },
  {
    id: "54",
    district_id: "5",
    name: "Chandpur Sadar",
    bn_name: "চাঁদপুর সদর",
    zip_code: "3600",
  },
  {
    id: "55",
    district_id: "5",
    name: "Matlab South",
    bn_name: "মতলব দক্ষিণ",
    zip_code: "3640",
  },
  {
    id: "56",
    district_id: "5",
    name: "Hajiganj",
    bn_name: "হাজীগঞ্জ",
    zip_code: "3610",
  },
  {
    id: "57",
    district_id: "5",
    name: "Matlab North",
    bn_name: "মতলব উত্তর",
    zip_code: "3650",
  },
  {
    id: "58",
    district_id: "5",
    name: "Faridgonj",
    bn_name: "ফরিদগঞ্জ",
    zip_code: "3620",
  },
  {
    id: "59",
    district_id: "6",
    name: "Lakshmipur Sadar",
    bn_name: "লক্ষ্মীপুর সদর",
    zip_code: "3700",
  },
  {
    id: "60",
    district_id: "6",
    name: "Kamalnagar",
    bn_name: "কমলনগর",
    zip_code: "3710",
  },
  {
    id: "61",
    district_id: "6",
    name: "Raipur",
    bn_name: "রায়পুর",
    zip_code: "3720",
  },
  {
    id: "62",
    district_id: "6",
    name: "Ramgati",
    bn_name: "রামগতি",
    zip_code: "3740",
  },
  {
    id: "63",
    district_id: "6",
    name: "Ramganj",
    bn_name: "রামগঞ্জ",
    zip_code: "3730",
  },
  {
    id: "64",
    district_id: "7",
    name: "Rangunia",
    bn_name: "রাঙ্গুনিয়া",
    zip_code: "4360",
  },
  {
    id: "65",
    district_id: "7",
    name: "Sitakunda",
    bn_name: "সীতাকুন্ড",
    zip_code: "4310",
  },
  {
    id: "66",
    district_id: "7",
    name: "Mirsharai",
    bn_name: "মীরসরাই",
    zip_code: "4320",
  },
  {
    id: "67",
    district_id: "7",
    name: "Patiya",
    bn_name: "পটিয়া",
    zip_code: "4375",
  },
  {
    id: "68",
    district_id: "7",
    name: "Sandwip",
    bn_name: "সন্দ্বীপ",
    zip_code: "4300",
  },
  {
    id: "69",
    district_id: "7",
    name: "Banshkhali",
    bn_name: "বাঁশখালী",
    zip_code: "4390",
  },
  {
    id: "70",
    district_id: "7",
    name: "Boalkhali",
    bn_name: "বোয়ালখালী",
    zip_code: "4365",
  },
  {
    id: "71",
    district_id: "7",
    name: "Anwara",
    bn_name: "আনোয়ারা",
    zip_code: "4376",
  },
  {
    id: "72",
    district_id: "7",
    name: "Chandanaish",
    bn_name: "চন্দনাইশ",
    zip_code: "4370",
  },
  {
    id: "73",
    district_id: "7",
    name: "Satkania",
    bn_name: "সাতকানিয়া",
    zip_code: "4386",
  },
  {
    id: "74",
    district_id: "7",
    name: "Lohagara",
    bn_name: "লোহাগাড়া",
    zip_code: "4379",
  },
  {
    id: "75",
    district_id: "7",
    name: "Hathazari",
    bn_name: "হাটহাজারী",
    zip_code: "4330",
  },
  {
    id: "76",
    district_id: "7",
    name: "Fatikchhari",
    bn_name: "ফটিকছড়ি",
    zip_code: "4350",
  },
  {
    id: "77",
    district_id: "7",
    name: "Raozan",
    bn_name: "রাউজান",
    zip_code: "4340",
  },
  {
    id: "78",
    district_id: "7",
    name: "Karnafuli",
    bn_name: "কর্ণফুলী",
    zip_code: "4373",
  },
  {
    id: "79",
    district_id: "8",
    name: "Cox's Bazar Sadar",
    bn_name: "কক্সবাজার সদর",
    zip_code: "4700",
  },
  {
    id: "80",
    district_id: "8",
    name: "Chakaria",
    bn_name: "চকরিয়া",
    zip_code: "4720",
  },
  {
    id: "81",
    district_id: "8",
    name: "Kutubdia",
    bn_name: "কুতুবদিয়া",
    zip_code: "4740",
  },
  {
    id: "82",
    district_id: "8",
    name: "Ukhiya",
    bn_name: "উখিয়া",
    zip_code: "4703",
  },
  {
    id: "83",
    district_id: "8",
    name: "Moheshkhali",
    bn_name: "মহেশখালী",
    zip_code: "4750",
  },
  {
    id: "84",
    district_id: "8",
    name: "Pekua",
    bn_name: "পেকুয়া",
    zip_code: "4730",
  },
  {
    id: "85",
    district_id: "8",
    name: "Ramu",
    bn_name: "রামু",
    zip_code: "4760",
  },
  {
    id: "86",
    district_id: "8",
    name: "Teknaf",
    bn_name: "টেকনাফ",
    zip_code: "4770",
  },
  {
    id: "87",
    district_id: "9",
    name: "Khagrachhari Sadar",
    bn_name: "খাগড়াছড়ি সদর",
    zip_code: "4400",
  },
  {
    id: "88",
    district_id: "9",
    name: "Dighinala",
    bn_name: "দিঘীনালা",
    zip_code: "4420",
  },
  {
    id: "89",
    district_id: "9",
    name: "Panchari",
    bn_name: "পানছড়ি",
    zip_code: "4430",
  },
  {
    id: "90",
    district_id: "9",
    name: "Laxmichhari",
    bn_name: "লক্ষীছড়ি",
    zip_code: "4480",
  },
  {
    id: "91",
    district_id: "9",
    name: "Mohalchari",
    bn_name: "মহালছড়ি",
    zip_code: "4440",
  },
  {
    id: "92",
    district_id: "9",
    name: "Manikchari",
    bn_name: "মানিকছড়ি",
    zip_code: "4450",
  },
  {
    id: "93",
    district_id: "9",
    name: "Ramgarh",
    bn_name: "রামগড়",
    zip_code: "4490",
  },
  {
    id: "94",
    district_id: "9",
    name: "Matiranga",
    bn_name: "মাটিরাঙ্গা",
    zip_code: "4460",
  },
  {
    id: "95",
    district_id: "9",
    name: "Guimara",
    bn_name: "গুইমারা",
    zip_code: "4480",
  },
  {
    id: "96",
    district_id: "10",
    name: "Bandarban Sadar",
    bn_name: "বান্দরবান সদর",
    zip_code: "4600",
  },
  {
    id: "97",
    district_id: "10",
    name: "Alikadam",
    bn_name: "আলীকদম",
    zip_code: "4620",
  },
  {
    id: "98",
    district_id: "10",
    name: "Naikhongchhari",
    bn_name: "নাইক্ষ্যংছড়ি",
    zip_code: "4670",
  },
  {
    id: "99",
    district_id: "10",
    name: "Rowangchhari",
    bn_name: "রোয়াংছড়ি",
    zip_code: "4660",
  },
  {
    id: "100",
    district_id: "10",
    name: "Lama",
    bn_name: "লামা",
    zip_code: "4650",
  },
  {
    id: "101",
    district_id: "10",
    name: "Ruma",
    bn_name: "রুমা",
    zip_code: "4680",
  },
  {
    id: "102",
    district_id: "10",
    name: "Thanchi",
    bn_name: "থানচি",
    zip_code: "4690",
  },
  {
    id: "103",
    district_id: "11",
    name: "Belkuchi",
    bn_name: "বেলকুচি",
    zip_code: "6740",
  },
  {
    id: "104",
    district_id: "11",
    name: "Chauhali",
    bn_name: "চৌহালি",
    zip_code: "6780",
  },
  {
    id: "105",
    district_id: "11",
    name: "Kamarkhand",
    bn_name: "কামারখন্দ",
    zip_code: "6760",
  },
  {
    id: "106",
    district_id: "11",
    name: "Kazipur",
    bn_name: "কাজীপুর",
    zip_code: "6750",
  },
  {
    id: "107",
    district_id: "11",
    name: "Raigonj",
    bn_name: "রায়গঞ্জ",
    zip_code: "6770",
  },
  {
    id: "108",
    district_id: "11",
    name: "Shahjadpur",
    bn_name: "শাহজাদপুর",
    zip_code: "6730",
  },
  {
    id: "109",
    district_id: "11",
    name: "Sirajganj Sadar",
    bn_name: "সিরাজগঞ্জ সদর",
    zip_code: "6700",
  },
  {
    id: "110",
    district_id: "11",
    name: "Tarash",
    bn_name: "তাড়াশ",
    zip_code: "6720",
  },
  {
    id: "111",
    district_id: "11",
    name: "Ullapara",
    bn_name: "উল্লাপাড়া",
    zip_code: "6710",
  },
  {
    id: "112",
    district_id: "12",
    name: "Sujanagar",
    bn_name: "সুজানগর",
    zip_code: "6660",
  },
  {
    id: "113",
    district_id: "12",
    name: "Ishurdi",
    bn_name: "ঈশ্বরদী",
    zip_code: "6620",
  },
  {
    id: "114",
    district_id: "12",
    name: "Bhangura",
    bn_name: "ভাঙ্গুড়া",
    zip_code: "6640",
  },
  {
    id: "115",
    district_id: "12",
    name: "Pabna Sadar",
    bn_name: "পাবনা সদর",
    zip_code: "6600",
  },
  {
    id: "116",
    district_id: "12",
    name: "Bera",
    bn_name: "বেড়া",
    zip_code: "6680",
  },
  {
    id: "117",
    district_id: "12",
    name: "Atghoria",
    bn_name: "আটঘরিয়া",
    zip_code: "6650",
  },
  {
    id: "118",
    district_id: "12",
    name: "Chatmohar",
    bn_name: "চাটমোহর",
    zip_code: "6630",
  },
  {
    id: "119",
    district_id: "12",
    name: "Santhia",
    bn_name: "সাঁথিয়া",
    zip_code: "6610",
  },
  {
    id: "120",
    district_id: "12",
    name: "Faridpur",
    bn_name: "ফরিদপুর",
    zip_code: "6620",
  },
  {
    id: "121",
    district_id: "13",
    name: "Kahaloo",
    bn_name: "কাহালু",
    zip_code: "5820",
  },
  {
    id: "122",
    district_id: "13",
    name: "Bogura Sadar",
    bn_name: "বগুড়া সদর",
    zip_code: "5810",
  },
  {
    id: "123",
    district_id: "13",
    name: "Shariakandi",
    bn_name: "সারিয়াকান্দি",
    zip_code: "5800",
  },
  {
    id: "124",
    district_id: "13",
    name: "Shajahanpur",
    bn_name: "শাজাহানপুর",
    zip_code: "5840",
  },
  {
    id: "125",
    district_id: "13",
    name: "Dupchanchia",
    bn_name: "দুপচাচিঁয়া",
    zip_code: "5850",
  },
  {
    id: "126",
    district_id: "13",
    name: "Adamdighi",
    bn_name: "আদমদিঘি",
    zip_code: "5810",
  },
  {
    id: "127",
    district_id: "13",
    name: "Nondigram",
    bn_name: "নন্দিগ্রাম",
    zip_code: "5830",
  },
  {
    id: "128",
    district_id: "13",
    name: "Sonatala",
    bn_name: "সোনাতলা",
    zip_code: "5825",
  },
  {
    id: "129",
    district_id: "13",
    name: "Dhunot",
    bn_name: "ধুনট",
    zip_code: "5850",
  },
  {
    id: "130",
    district_id: "13",
    name: "Gabtali",
    bn_name: "গাবতলী",
    zip_code: "5870",
  },
  {
    id: "131",
    district_id: "13",
    name: "Sherpur",
    bn_name: "শেরপুর",
    zip_code: "5890",
  },
  {
    id: "132",
    district_id: "13",
    name: "Shibganj",
    bn_name: "শিবগঞ্জ",
    zip_code: "5812",
  },
  {
    id: "133",
    district_id: "14",
    name: "Paba",
    bn_name: "পবা",
    zip_code: "6000",
  },
  {
    id: "134",
    district_id: "14",
    name: "Durgapur",
    bn_name: "দুর্গাপুর",
    zip_code: "6240",
  },
  {
    id: "135",
    district_id: "14",
    name: "Mohonpur",
    bn_name: "মোহনপুর",
    zip_code: "6260",
  },
  {
    id: "136",
    district_id: "14",
    name: "Charghat",
    bn_name: "চারঘাট",
    zip_code: "6230",
  },
  {
    id: "137",
    district_id: "14",
    name: "Puthia",
    bn_name: "পুঠিয়া",
    zip_code: "6270",
  },
  {
    id: "138",
    district_id: "14",
    name: "Bagha",
    bn_name: "বাঘা",
    zip_code: "6210",
  },
  {
    id: "139",
    district_id: "14",
    name: "Godagari",
    bn_name: "গোদাগাড়ী",
    zip_code: "6220",
  },
  {
    id: "140",
    district_id: "14",
    name: "Tanore",
    bn_name: "তানোর",
    zip_code: "6280",
  },
  {
    id: "141",
    district_id: "14",
    name: "Bagmara",
    bn_name: "বাগমারা",
    zip_code: "6250",
  },
  {
    id: "142",
    district_id: "15",
    name: "Natore Sadar",
    bn_name: "নাটোর সদর",
    zip_code: "6400",
  },
  {
    id: "143",
    district_id: "15",
    name: "Singra",
    bn_name: "সিংড়া",
    zip_code: "6410",
  },
  {
    id: "144",
    district_id: "15",
    name: "Baraigram",
    bn_name: "বড়াইগ্রাম",
    zip_code: "6430",
  },
  {
    id: "145",
    district_id: "15",
    name: "Bagatipara",
    bn_name: "বাগাতিপাড়া",
    zip_code: "6450",
  },
  {
    id: "146",
    district_id: "15",
    name: "Lalpur",
    bn_name: "লালপুর",
    zip_code: "6420",
  },
  {
    id: "147",
    district_id: "15",
    name: "Gurudaspur",
    bn_name: "গুরুদাসপুর",
    zip_code: "6440",
  },
  {
    id: "148",
    district_id: "15",
    name: "Naldanga",
    bn_name: "নলডাঙ্গা",
    zip_code: "6460",
  },
  {
    id: "149",
    district_id: "16",
    name: "Akkelpur",
    bn_name: "আক্কেলপুর",
    zip_code: "5940",
  },
  {
    id: "150",
    district_id: "16",
    name: "Kalai",
    bn_name: "কালাই",
    zip_code: "5920",
  },
  {
    id: "151",
    district_id: "16",
    name: "Khetlal",
    bn_name: "ক্ষেতলাল",
    zip_code: "5930",
  },
  {
    id: "152",
    district_id: "16",
    name: "Panchbibi",
    bn_name: "পাঁচবিবি",
    zip_code: "5910",
  },
  {
    id: "153",
    district_id: "16",
    name: "Joypurhat Sadar",
    bn_name: "জয়পুরহাট সদর",
    zip_code: "5900",
  },
  {
    id: "154",
    district_id: "17",
    name: "Chapainawabganj Sadar",
    bn_name: "চাঁপাইনবাবগঞ্জ সদর",
    zip_code: "6300",
  },
  {
    id: "155",
    district_id: "17",
    name: "Gomostapur",
    bn_name: "গোমস্তাপুর",
    zip_code: "6330",
  },
  {
    id: "156",
    district_id: "17",
    name: "Nachol",
    bn_name: "নাচোল",
    zip_code: "6340",
  },
  {
    id: "157",
    district_id: "17",
    name: "Bholahat",
    bn_name: "ভোলাহাট",
    zip_code: "6320",
  },
  {
    id: "158",
    district_id: "17",
    name: "Shibganj",
    bn_name: "শিবগঞ্জ",
    zip_code: "6310",
  },
  {
    id: "159",
    district_id: "18",
    name: "Mohadevpur",
    bn_name: "মহাদেবপুর",
    zip_code: "6570",
  },
  {
    id: "160",
    district_id: "18",
    name: "Badalgachi",
    bn_name: "বদলগাছী",
    zip_code: "6520",
  },
  {
    id: "161",
    district_id: "18",
    name: "Patnitala",
    bn_name: "পত্নিতলা",
    zip_code: "6560",
  },
  {
    id: "162",
    district_id: "18",
    name: "Dhamoirhat",
    bn_name: "ধামইরহাট",
    zip_code: "6590",
  },
  {
    id: "163",
    district_id: "18",
    name: "Niamatpur",
    bn_name: "নিয়ামতপুর",
    zip_code: "6580",
  },
  {
    id: "164",
    district_id: "18",
    name: "Manda",
    bn_name: "মান্দা",
    zip_code: "6530",
  },
  {
    id: "165",
    district_id: "18",
    name: "Atrai",
    bn_name: "আত্রাই",
    zip_code: "6510",
  },
  {
    id: "166",
    district_id: "18",
    name: "Raninagar",
    bn_name: "রাণীনগর",
    zip_code: "6550",
  },
  {
    id: "167",
    district_id: "18",
    name: "Naogaon Sadar",
    bn_name: "নওগাঁ সদর",
    zip_code: "6500",
  },
  {
    id: "168",
    district_id: "18",
    name: "Porsha",
    bn_name: "পোরশা",
    zip_code: "6540",
  },
  {
    id: "169",
    district_id: "18",
    name: "Sapahar",
    bn_name: "সাপাহার",
    zip_code: "6515",
  },
  {
    id: "170",
    district_id: "19",
    name: "Manirampur",
    bn_name: "মণিরামপুর",
    zip_code: "7440",
  },
  {
    id: "171",
    district_id: "19",
    name: "Abhaynagar",
    bn_name: "অভয়নগর",
    zip_code: "7460",
  },
  {
    id: "172",
    district_id: "19",
    name: "Bagherpara",
    bn_name: "বাঘারপাড়া",
    zip_code: "7470",
  },
  {
    id: "173",
    district_id: "19",
    name: "Chougachha",
    bn_name: "চৌগাছা",
    zip_code: "7410",
  },
  {
    id: "174",
    district_id: "19",
    name: "Jhikargacha",
    bn_name: "ঝিকরগাছা",
    zip_code: "7420",
  },
  {
    id: "175",
    district_id: "19",
    name: "Keshabpur",
    bn_name: "কেশবপুর",
    zip_code: "7450",
  },
  {
    id: "176",
    district_id: "19",
    name: "Jashore Sadar",
    bn_name: "যশোর সদর",
    zip_code: "7400",
  },
  {
    id: "177",
    district_id: "19",
    name: "Sharsha",
    bn_name: "শার্শা",
    zip_code: "7430",
  },
  {
    id: "178",
    district_id: "20",
    name: "Assasuni",
    bn_name: "আশাশুনি",
    zip_code: "9450",
  },
  {
    id: "179",
    district_id: "20",
    name: "Debhata",
    bn_name: "দেবহাটা",
    zip_code: "9430",
  },
  {
    id: "180",
    district_id: "20",
    name: "Kalaroa",
    bn_name: "কলারোয়া",
    zip_code: "9410",
  },
  {
    id: "181",
    district_id: "20",
    name: "Satkhira Sadar",
    bn_name: "সাতক্ষীরা সদর",
    zip_code: "9400",
  },
  {
    id: "182",
    district_id: "20",
    name: "Shyamnagar",
    bn_name: "শ্যামনগর",
    zip_code: "9460",
  },
  {
    id: "183",
    district_id: "20",
    name: "Tala",
    bn_name: "তালা",
    zip_code: "9440",
  },
  {
    id: "184",
    district_id: "20",
    name: "Kaliganj",
    bn_name: "কালিগঞ্জ",
    zip_code: "9420",
  },
  {
    id: "185",
    district_id: "21",
    name: "Mujibnagar",
    bn_name: "মুজিবনগর",
    zip_code: "7102",
  },
  {
    id: "186",
    district_id: "21",
    name: "Meherpur Sadar",
    bn_name: "মেহেরপুর সদর",
    zip_code: "7100",
  },
  {
    id: "187",
    district_id: "21",
    name: "Gangni",
    bn_name: "গাংনী",
    zip_code: "7110",
  },
  {
    id: "188",
    district_id: "22",
    name: "Narail Sadar",
    bn_name: "নড়াইল সদর",
    zip_code: "7500",
  },
  {
    id: "189",
    district_id: "22",
    name: "Lohagara",
    bn_name: "লোহাগড়া",
    zip_code: "7510",
  },
  {
    id: "190",
    district_id: "22",
    name: "Kalia",
    bn_name: "কালিয়া",
    zip_code: "7520",
  },
  {
    id: "191",
    district_id: "23",
    name: "Chuadanga Sadar",
    bn_name: "চুয়াডাঙ্গা সদর",
    zip_code: "7200",
  },
  {
    id: "192",
    district_id: "23",
    name: "Alamdanga",
    bn_name: "আলমডাঙ্গা",
    zip_code: "7210",
  },
  {
    id: "193",
    district_id: "23",
    name: "Damurhuda",
    bn_name: "দামুড়হুদা",
    zip_code: "7220",
  },
  {
    id: "194",
    district_id: "23",
    name: "Jibannagar",
    bn_name: "জীবননগর",
    zip_code: "7230",
  },
  {
    id: "195",
    district_id: "24",
    name: "Kushtia Sadar",
    bn_name: "কুষ্টিয়া সদর",
    zip_code: "7000",
  },
  {
    id: "196",
    district_id: "24",
    name: "Kumarkhali",
    bn_name: "কুমারখালী",
    zip_code: "7010",
  },
  {
    id: "197",
    district_id: "24",
    name: "Khoksa",
    bn_name: "খোকসা",
    zip_code: "7020",
  },
  {
    id: "198",
    district_id: "24",
    name: "Mirpur",
    bn_name: "মিরপুর",
    zip_code: "7030",
  },
  {
    id: "199",
    district_id: "24",
    name: "Daulatpur",
    bn_name: "দৌলতপুর",
    zip_code: "7050",
  },
  {
    id: "200",
    district_id: "24",
    name: "Bheramara",
    bn_name: "ভেড়ামারা",
    zip_code: "7040",
  },
  {
    id: "201",
    district_id: "25",
    name: "Shalikha",
    bn_name: "শালিখা",
    zip_code: "7630",
  },
  {
    id: "202",
    district_id: "25",
    name: "Sreepur",
    bn_name: "শ্রীপুর",
    zip_code: "7610",
  },
  {
    id: "203",
    district_id: "25",
    name: "Magura Sadar",
    bn_name: "মাগুরা সদর",
    zip_code: "7600",
  },
  {
    id: "204",
    district_id: "25",
    name: "Mohammadpur",
    bn_name: "মহম্মদপুর",
    zip_code: "7620",
  },
  {
    id: "205",
    district_id: "26",
    name: "Paikgasa",
    bn_name: "পাইকগাছা",
    zip_code: "9280",
  },
  {
    id: "206",
    district_id: "26",
    name: "Fultola",
    bn_name: "ফুলতলা",
    zip_code: "9210",
  },
  {
    id: "207",
    district_id: "26",
    name: "Digholia",
    bn_name: "দিঘলিয়া",
    zip_code: "9260",
  },
  {
    id: "208",
    district_id: "26",
    name: "Rupsha",
    bn_name: "রূপসা",
    zip_code: "9240",
  },
  {
    id: "209",
    district_id: "26",
    name: "Terokhada",
    bn_name: "তেরখাদা",
    zip_code: "9230",
  },
  {
    id: "210",
    district_id: "26",
    name: "Dumuria",
    bn_name: "ডুমুরিয়া",
    zip_code: "9250",
  },
  {
    id: "211",
    district_id: "26",
    name: "Botiaghata",
    bn_name: "বটিয়াঘাটা",
    zip_code: "9260",
  },
  {
    id: "212",
    district_id: "26",
    name: "Dakop",
    bn_name: "দাকোপ",
    zip_code: "9270",
  },
  {
    id: "213",
    district_id: "26",
    name: "Koyra",
    bn_name: "কয়রা",
    zip_code: "9290",
  },
  {
    id: "214",
    district_id: "27",
    name: "Fakirhat",
    bn_name: "ফকিরহাট",
    zip_code: "9370",
  },
  {
    id: "215",
    district_id: "27",
    name: "Bagerhat Sadar",
    bn_name: "বাগেরহাট সদর",
    zip_code: "9300",
  },
  {
    id: "216",
    district_id: "27",
    name: "Mollahat",
    bn_name: "মোল্লাহাট",
    zip_code: "9380",
  },
  {
    id: "217",
    district_id: "27",
    name: "Sarankhola",
    bn_name: "শরণখোলা",
    zip_code: "9390",
  },
  {
    id: "218",
    district_id: "27",
    name: "Rampal",
    bn_name: "রামপাল",
    zip_code: "9340",
  },
  {
    id: "219",
    district_id: "27",
    name: "Morrelganj",
    bn_name: "মোড়েলগঞ্জ",
    zip_code: "9360",
  },
  {
    id: "220",
    district_id: "27",
    name: "Kachua",
    bn_name: "কচুয়া",
    zip_code: "9330",
  },
  {
    id: "221",
    district_id: "27",
    name: "Mongla",
    bn_name: "মোংলা",
    zip_code: "9351",
  },
  {
    id: "222",
    district_id: "27",
    name: "Chitalmari",
    bn_name: "চিতলমারী",
    zip_code: "9350",
  },
  {
    id: "223",
    district_id: "28",
    name: "Jhenaidah Sadar",
    bn_name: "ঝিনাইদহ সদর",
    zip_code: "7300",
  },
  {
    id: "224",
    district_id: "28",
    name: "Shailkupa",
    bn_name: "শৈলকুপা",
    zip_code: "7310",
  },
  {
    id: "225",
    district_id: "28",
    name: "Harinakundu",
    bn_name: "হরিণাকুন্ডু",
    zip_code: "7350",
  },
  {
    id: "226",
    district_id: "28",
    name: "Kaliganj",
    bn_name: "কালীগঞ্জ",
    zip_code: "7320",
  },
  {
    id: "227",
    district_id: "28",
    name: "Kotchandpur",
    bn_name: "কোটচাঁদপুর",
    zip_code: "7330",
  },
  {
    id: "228",
    district_id: "28",
    name: "Moheshpur",
    bn_name: "মহেশপুর",
    zip_code: "7340",
  },
  {
    id: "229",
    district_id: "29",
    name: "Jhalakathi Sadar",
    bn_name: "ঝালকাঠি সদর",
    zip_code: "8400",
  },
  {
    id: "230",
    district_id: "29",
    name: "Kathalia",
    bn_name: "কাঠালিয়া",
    zip_code: "8420",
  },
  {
    id: "231",
    district_id: "29",
    name: "Nalchity",
    bn_name: "নলছিটি",
    zip_code: "8430",
  },
  {
    id: "232",
    district_id: "29",
    name: "Rajapur",
    bn_name: "রাজাপুর",
    zip_code: "8440",
  },
  {
    id: "233",
    district_id: "30",
    name: "Bauphal",
    bn_name: "বাউফল",
    zip_code: "8620",
  },
  {
    id: "234",
    district_id: "30",
    name: "Patuakhali Sadar",
    bn_name: "পটুয়াখালী সদর",
    zip_code: "8600",
  },
  {
    id: "235",
    district_id: "30",
    name: "Dumki",
    bn_name: "দুমকি",
    zip_code: "8640",
  },
  {
    id: "236",
    district_id: "30",
    name: "Dashmina",
    bn_name: "দশমিনা",
    zip_code: "8630",
  },
  {
    id: "237",
    district_id: "30",
    name: "Kalapara",
    bn_name: "কলাপাড়া",
    zip_code: "8660",
  },
  {
    id: "238",
    district_id: "30",
    name: "Mirzaganj",
    bn_name: "মির্জাগঞ্জ",
    zip_code: "8670",
  },
  {
    id: "239",
    district_id: "30",
    name: "Galachipa",
    bn_name: "গলাচিপা",
    zip_code: "8650",
  },
  {
    id: "240",
    district_id: "30",
    name: "Rangabali",
    bn_name: "রাঙ্গাবালী",
    zip_code: "8680",
  },
  {
    id: "241",
    district_id: "31",
    name: "Pirojpur Sadar",
    bn_name: "পিরোজপুর সদর",
    zip_code: "8500",
  },
  {
    id: "242",
    district_id: "31",
    name: "Nazirpur",
    bn_name: "নাজিরপুর",
    zip_code: "8550",
  },
  {
    id: "243",
    district_id: "31",
    name: "Kawkhali",
    bn_name: "কাউখালী",
    zip_code: "8530",
  },
  {
    id: "244",
    district_id: "31",
    name: "Zianagar",
    bn_name: "জিয়ানগর",
    zip_code: "8510",
  },
  {
    id: "245",
    district_id: "31",
    name: "Bhandaria",
    bn_name: "ভান্ডারিয়া",
    zip_code: "8510",
  },
  {
    id: "246",
    district_id: "31",
    name: "Mathbaria",
    bn_name: "মঠবাড়ীয়া",
    zip_code: "8540",
  },
  {
    id: "247",
    district_id: "31",
    name: "Nesharabad",
    bn_name: "নেছারাবাদ",
    zip_code: "8560",
  },
  {
    id: "248",
    district_id: "32",
    name: "Barishal Sadar",
    bn_name: "বরিশাল সদর",
    zip_code: "8200",
  },
  {
    id: "249",
    district_id: "32",
    name: "Bakerganj",
    bn_name: "বাকেরগঞ্জ",
    zip_code: "8220",
  },
  {
    id: "250",
    district_id: "32",
    name: "Babuganj",
    bn_name: "বাবুগঞ্জ",
    zip_code: "8210",
  },
  {
    id: "251",
    district_id: "32",
    name: "Wazirpur",
    bn_name: "উজিরপুর",
    zip_code: "8290",
  },
  {
    id: "252",
    district_id: "32",
    name: "Banaripara",
    bn_name: "বানারীপাড়া",
    zip_code: "8230",
  },
  {
    id: "253",
    district_id: "32",
    name: "Gournadi",
    bn_name: "গৌরনদী",
    zip_code: "8240",
  },
  {
    id: "254",
    district_id: "32",
    name: "Agailjhara",
    bn_name: "আগৈলঝাড়া",
    zip_code: "8250",
  },
  {
    id: "255",
    district_id: "32",
    name: "Mehendiganj",
    bn_name: "মেহেন্দিগঞ্জ",
    zip_code: "8270",
  },
  {
    id: "256",
    district_id: "32",
    name: "Muladi",
    bn_name: "মুলাদী",
    zip_code: "8280",
  },
  {
    id: "257",
    district_id: "32",
    name: "Hizla",
    bn_name: "হিজলা",
    zip_code: "8260",
  },
  {
    id: "258",
    district_id: "33",
    name: "Bhola Sadar",
    bn_name: "ভোলা সদর",
    zip_code: "8300",
  },
  {
    id: "259",
    district_id: "33",
    name: "Borhan Sddin",
    bn_name: "বোরহান উদ্দিন",
    zip_code: "8320",
  },
  {
    id: "260",
    district_id: "33",
    name: "Charfesson",
    bn_name: "চরফ্যাশন",
    zip_code: "8340",
  },
  {
    id: "261",
    district_id: "33",
    name: "Doulatkhan",
    bn_name: "দৌলতখান",
    zip_code: "8350",
  },
  {
    id: "262",
    district_id: "33",
    name: "Monpura",
    bn_name: "মনপুরা",
    zip_code: "8370",
  },
  {
    id: "263",
    district_id: "33",
    name: "Tazumuddin",
    bn_name: "তজুমদ্দিন",
    zip_code: "8380",
  },
  {
    id: "264",
    district_id: "33",
    name: "Lalmohan",
    bn_name: "লালমোহন",
    zip_code: "8360",
  },
  {
    id: "265",
    district_id: "34",
    name: "Amtali",
    bn_name: "আমতলী",
    zip_code: "8730",
  },
  {
    id: "266",
    district_id: "34",
    name: "Barguna Sadar",
    bn_name: "বরগুনা সদর",
    zip_code: "8700",
  },
  {
    id: "267",
    district_id: "34",
    name: "Betagi",
    bn_name: "বেতাগী",
    zip_code: "8710",
  },
  {
    id: "268",
    district_id: "34",
    name: "Bamna",
    bn_name: "বামনা",
    zip_code: "8740",
  },
  {
    id: "269",
    district_id: "34",
    name: "Pathorghata",
    bn_name: "পাথরঘাটা",
    zip_code: "8750",
  },
  {
    id: "270",
    district_id: "34",
    name: "Taltali",
    bn_name: "তালতলি",
    zip_code: "8760",
  },
  {
    id: "271",
    district_id: "35",
    name: "Balaganj",
    bn_name: "বালাগঞ্জ",
    zip_code: "3120",
  },
  {
    id: "272",
    district_id: "35",
    name: "Beanibazar",
    bn_name: "বিয়ানীবাজার",
    zip_code: "3170",
  },
  {
    id: "273",
    district_id: "35",
    name: "Bishwanath",
    bn_name: "বিশ্বনাথ",
    zip_code: "3130",
  },
  {
    id: "274",
    district_id: "35",
    name: "Companiganj",
    bn_name: "কোম্পানীগঞ্জ",
    zip_code: "3150",
  },
  {
    id: "275",
    district_id: "35",
    name: "Fenchuganj",
    bn_name: "ফেঞ্চুগঞ্জ",
    zip_code: "3116",
  },
  {
    id: "276",
    district_id: "35",
    name: "Golapganj",
    bn_name: "গোলাপগঞ্জ",
    zip_code: "3160",
  },
  {
    id: "277",
    district_id: "35",
    name: "Gowainghat",
    bn_name: "গোয়াইনঘাট",
    zip_code: "3113",
  },
  {
    id: "278",
    district_id: "35",
    name: "Jaintiapur",
    bn_name: "জৈন্তাপুর",
    zip_code: "3156",
  },
  {
    id: "279",
    district_id: "35",
    name: "Kanaighat",
    bn_name: "কানাইঘাট",
    zip_code: "3180",
  },
  {
    id: "280",
    district_id: "35",
    name: "Sylhet Sadar",
    bn_name: "সিলেট সদর",
    zip_code: "3100",
  },
  {
    id: "281",
    district_id: "35",
    name: "Zakiganj",
    bn_name: "জকিগঞ্জ",
    zip_code: "3190",
  },
  {
    id: "282",
    district_id: "35",
    name: "Dakshinsurma",
    bn_name: "দক্ষিণ সুরমা",
    zip_code: "3112",
  },
  {
    id: "283",
    district_id: "35",
    name: "Osmaninagar",
    bn_name: "ওসমানী নগর",
    zip_code: "3110",
  },
  {
    id: "284",
    district_id: "36",
    name: "Barlekha",
    bn_name: "বড়লেখা",
    zip_code: "3250",
  },
  {
    id: "285",
    district_id: "36",
    name: "Kamolganj",
    bn_name: "কমলগঞ্জ",
    zip_code: "3270",
  },
  {
    id: "286",
    district_id: "36",
    name: "Kulaura",
    bn_name: "কুলাউড়া",
    zip_code: "3230",
  },
  {
    id: "287",
    district_id: "36",
    name: "Moulvibazar Sadar",
    bn_name: "মৌলভীবাজার সদর",
    zip_code: "3200",
  },
  {
    id: "288",
    district_id: "36",
    name: "Rajnagar",
    bn_name: "রাজনগর",
    zip_code: "3240",
  },
  {
    id: "289",
    district_id: "36",
    name: "Sreemangal",
    bn_name: "শ্রীমঙ্গল",
    zip_code: "3210",
  },
  {
    id: "290",
    district_id: "36",
    name: "Juri",
    bn_name: "জুড়ী",
    zip_code: "3260",
  },
  {
    id: "291",
    district_id: "37",
    name: "Nabiganj",
    bn_name: "নবীগঞ্জ",
    zip_code: "3310",
  },
  {
    id: "292",
    district_id: "37",
    name: "Bahubal",
    bn_name: "বাহুবল",
    zip_code: "3350",
  },
  {
    id: "293",
    district_id: "37",
    name: "Ajmiriganj",
    bn_name: "আজমিরীগঞ্জ",
    zip_code: "3360",
  },
  {
    id: "294",
    district_id: "37",
    name: "Baniachong",
    bn_name: "বানিয়াচং",
    zip_code: "3370",
  },
  {
    id: "295",
    district_id: "37",
    name: "Lakhai",
    bn_name: "লাখাই",
    zip_code: "3380",
  },
  {
    id: "296",
    district_id: "37",
    name: "Chunarughat",
    bn_name: "চুনারুঘাট",
    zip_code: "3340",
  },
  {
    id: "297",
    district_id: "37",
    name: "Habiganj Sadar",
    bn_name: "হবিগঞ্জ সদর",
    zip_code: "3300",
  },
  {
    id: "298",
    district_id: "37",
    name: "Madhabpur",
    bn_name: "মাধবপুর",
    zip_code: "3330",
  },
  {
    id: "299",
    district_id: "38",
    name: "Sunamganj Sadar",
    bn_name: "সুনামগঞ্জ সদর",
    zip_code: "3000",
  },
  {
    id: "300",
    district_id: "38",
    name: "Shantiganj",
    bn_name: "শান্তিগঞ্জ",
    zip_code: "3080",
  },
  {
    id: "301",
    district_id: "38",
    name: "Bishwambarpur",
    bn_name: "বিশ্বম্ভরপুর",
    zip_code: "3080",
  },
  {
    id: "302",
    district_id: "38",
    name: "Chhatak",
    bn_name: "ছাতক",
    zip_code: "3060",
  },
  {
    id: "303",
    district_id: "38",
    name: "Jagannathpur",
    bn_name: "জগন্নাথপুর",
    zip_code: "3030",
  },
  {
    id: "304",
    district_id: "38",
    name: "Dowarabazar",
    bn_name: "দোয়ারাবাজার",
    zip_code: "3040",
  },
  {
    id: "305",
    district_id: "38",
    name: "Tahirpur",
    bn_name: "তাহিরপুর",
    zip_code: "3095",
  },
  {
    id: "306",
    district_id: "38",
    name: "Dharmapasha",
    bn_name: "ধর্মপাশা",
    zip_code: "3070",
  },
  {
    id: "307",
    district_id: "38",
    name: "Jamalganj",
    bn_name: "জামালগঞ্জ",
    zip_code: "3010",
  },
  {
    id: "308",
    district_id: "38",
    name: "Shalla",
    bn_name: "শাল্লা",
    zip_code: "3050",
  },
  {
    id: "309",
    district_id: "38",
    name: "Derai",
    bn_name: "দিরাই",
    zip_code: "3050",
  },
  {
    id: "310",
    district_id: "39",
    name: "Belabo",
    bn_name: "বেলাবো",
    zip_code: "1640",
  },
  {
    id: "311",
    district_id: "39",
    name: "Monohardi",
    bn_name: "মনোহরদী",
    zip_code: "1630",
  },
  {
    id: "312",
    district_id: "39",
    name: "Narsingdi Sadar",
    bn_name: "নরসিংদী সদর",
    zip_code: "1600",
  },
  {
    id: "313",
    district_id: "39",
    name: "Palash",
    bn_name: "পলাশ",
    zip_code: "1620",
  },
  {
    id: "314",
    district_id: "39",
    name: "Raipura",
    bn_name: "রায়পুরা",
    zip_code: "1610",
  },
  {
    id: "315",
    district_id: "39",
    name: "Shibpur",
    bn_name: "শিবপুর",
    zip_code: "1650",
  },
  {
    id: "316",
    district_id: "40",
    name: "Kaliganj",
    bn_name: "কালীগঞ্জ",
    zip_code: "1720",
  },
  {
    id: "317",
    district_id: "40",
    name: "Kaliakair",
    bn_name: "কালিয়াকৈর",
    zip_code: "1750",
  },
  {
    id: "318",
    district_id: "40",
    name: "Kapasia",
    bn_name: "কাপাসিয়া",
    zip_code: "1730",
  },
  {
    id: "319",
    district_id: "40",
    name: "Gazipur Sadar",
    bn_name: "গাজীপুর সদর",
    zip_code: "1700",
  },
  {
    id: "320",
    district_id: "40",
    name: "Sreepur",
    bn_name: "শ্রীপুর",
    zip_code: "1740",
  },
  {
    id: "321",
    district_id: "41",
    name: "Shariatpur Sadar",
    bn_name: "শরিয়তপুর সদর",
    zip_code: "8000",
  },
  {
    id: "322",
    district_id: "41",
    name: "Naria",
    bn_name: "নড়িয়া",
    zip_code: "8010",
  },
  {
    id: "323",
    district_id: "41",
    name: "Zajira",
    bn_name: "জাজিরা",
    zip_code: "8020",
  },
  {
    id: "324",
    district_id: "41",
    name: "Gosairhat",
    bn_name: "গোসাইরহাট",
    zip_code: "8050",
  },
  {
    id: "325",
    district_id: "41",
    name: "Bhedarganj",
    bn_name: "ভেদরগঞ্জ",
    zip_code: "8030",
  },
  {
    id: "326",
    district_id: "41",
    name: "Damudya",
    bn_name: "ডামুড্যা",
    zip_code: "8040",
  },
  {
    id: "327",
    district_id: "42",
    name: "Araihazar",
    bn_name: "আড়াইহাজার",
    zip_code: "1450",
  },
  {
    id: "328",
    district_id: "42",
    name: "Bandar",
    bn_name: "বন্দর",
    zip_code: "1410",
  },
  {
    id: "329",
    district_id: "42",
    name: "Narayanganj Sadar",
    bn_name: "নারায়নগঞ্জ সদর",
    zip_code: "1400",
  },
  {
    id: "330",
    district_id: "42",
    name: "Rupganj",
    bn_name: "রূপগঞ্জ",
    zip_code: "1460",
  },
  {
    id: "331",
    district_id: "42",
    name: "Sonargaon",
    bn_name: "সোনারগাঁ",
    zip_code: "1440",
  },
  {
    id: "332",
    district_id: "43",
    name: "Basail",
    bn_name: "বাসাইল",
    zip_code: "1970",
  },
  {
    id: "333",
    district_id: "43",
    name: "Bhuapur",
    bn_name: "ভুয়াপুর",
    zip_code: "1980",
  },
  {
    id: "334",
    district_id: "43",
    name: "Delduar",
    bn_name: "দেলদুয়ার",
    zip_code: "1910",
  },
  {
    id: "335",
    district_id: "43",
    name: "Ghatail",
    bn_name: "ঘাটাইল",
    zip_code: "1940",
  },
  {
    id: "336",
    district_id: "43",
    name: "Gopalpur",
    bn_name: "গোপালপুর",
    zip_code: "1920",
  },
  {
    id: "337",
    district_id: "43",
    name: "Madhupur",
    bn_name: "মধুপুর",
    zip_code: "1996",
  },
  {
    id: "338",
    district_id: "43",
    name: "Mirzapur",
    bn_name: "মির্জাপুর",
    zip_code: "1930",
  },
  {
    id: "339",
    district_id: "43",
    name: "Nagarpur",
    bn_name: "নাগরপুর",
    zip_code: "1936",
  },
  {
    id: "340",
    district_id: "43",
    name: "Sakhipur",
    bn_name: "সখিপুর",
    zip_code: "1960",
  },
  {
    id: "341",
    district_id: "43",
    name: "Tangail Sadar",
    bn_name: "টাঙ্গাইল সদর",
    zip_code: "1900",
  },
  {
    id: "342",
    district_id: "43",
    name: "Kalihati",
    bn_name: "কালিহাতী",
    zip_code: "1950",
  },
  {
    id: "343",
    district_id: "43",
    name: "Dhanbari",
    bn_name: "ধনবাড়ী",
    zip_code: "1990",
  },
  {
    id: "344",
    district_id: "44",
    name: "Itna",
    bn_name: "ইটনা",
    zip_code: "2390",
  },
  {
    id: "345",
    district_id: "44",
    name: "Katiadi",
    bn_name: "কটিয়াদী",
    zip_code: "2330",
  },
  {
    id: "346",
    district_id: "44",
    name: "Bhairab",
    bn_name: "ভৈরব",
    zip_code: "2350",
  },
  {
    id: "347",
    district_id: "44",
    name: "Tarail",
    bn_name: "তাড়াইল",
    zip_code: "2316",
  },
  {
    id: "348",
    district_id: "44",
    name: "Hossainpur",
    bn_name: "হোসেনপুর",
    zip_code: "2340",
  },
  {
    id: "349",
    district_id: "44",
    name: "Pakundia",
    bn_name: "পাকুন্দিয়া",
    zip_code: "2326",
  },
  {
    id: "350",
    district_id: "44",
    name: "Kuliarchar",
    bn_name: "কুলিয়ারচর",
    zip_code: "2380",
  },
  {
    id: "351",
    district_id: "44",
    name: "Kishoreganj Sadar",
    bn_name: "কিশোরগঞ্জ সদর",
    zip_code: "2300",
  },
  {
    id: "352",
    district_id: "44",
    name: "Karimgonj",
    bn_name: "করিমগঞ্জ",
    zip_code: "2310",
  },
  {
    id: "353",
    district_id: "44",
    name: "Bajitpur",
    bn_name: "বাজিতপুর",
    zip_code: "2336",
  },
  {
    id: "354",
    district_id: "44",
    name: "Austagram",
    bn_name: "অষ্টগ্রাম",
    zip_code: "2350",
  },
  {
    id: "355",
    district_id: "44",
    name: "Mithamoin",
    bn_name: "মিঠামইন",
    zip_code: "2370",
  },
  {
    id: "356",
    district_id: "44",
    name: "Nikli",
    bn_name: "নিকলী",
    zip_code: "2360",
  },
  {
    id: "357",
    district_id: "45",
    name: "Harirampur",
    bn_name: "হরিরামপুর",
    zip_code: "1850",
  },
  {
    id: "358",
    district_id: "45",
    name: "Saturia",
    bn_name: "সাটুরিয়া",
    zip_code: "1820",
  },
  {
    id: "359",
    district_id: "45",
    name: "Manikganj Sadar",
    bn_name: "মানিকগঞ্জ সদর",
    zip_code: "1800",
  },
  {
    id: "360",
    district_id: "45",
    name: "Gior",
    bn_name: "ঘিওর",
    zip_code: "1840",
  },
  {
    id: "361",
    district_id: "45",
    name: "Shibaloy",
    bn_name: "শিবালয়",
    zip_code: "1860",
  },
  {
    id: "362",
    district_id: "45",
    name: "Doulatpur",
    bn_name: "দৌলতপুর",
    zip_code: "1860",
  },
  {
    id: "363",
    district_id: "45",
    name: "Singiar",
    bn_name: "সিংগাইর",
    zip_code: "1810",
  },
  {
    id: "364",
    district_id: "46",
    name: "Savar",
    bn_name: "সাভার",
    zip_code: "1340",
  },
  {
    id: "365",
    district_id: "46",
    name: "Dhamrai",
    bn_name: "ধামরাই",
    zip_code: "1350",
  },
  {
    id: "366",
    district_id: "46",
    name: "Keraniganj",
    bn_name: "কেরাণীগঞ্জ",
    zip_code: "1310",
  },
  {
    id: "367",
    district_id: "46",
    name: "Nawabganj",
    bn_name: "নবাবগঞ্জ",
    zip_code: "1320",
  },
  {
    id: "368",
    district_id: "46",
    name: "Dohar",
    bn_name: "দোহার",
    zip_code: "1360",
  },
  {
    id: "369",
    district_id: "47",
    name: "Munshiganj Sadar",
    bn_name: "মুন্সিগঞ্জ সদর",
    zip_code: "1500",
  },
  {
    id: "370",
    district_id: "47",
    name: "Sreenagar",
    bn_name: "শ্রীনগর",
    zip_code: "1540",
  },
  {
    id: "371",
    district_id: "47",
    name: "Sirajdikhan",
    bn_name: "সিরাজদিখান",
    zip_code: "1530",
  },
  {
    id: "372",
    district_id: "47",
    name: "Louhajanj",
    bn_name: "লৌহজং",
    zip_code: "1520",
  },
  {
    id: "373",
    district_id: "47",
    name: "Gajaria",
    bn_name: "গজারিয়া",
    zip_code: "1510",
  },
  {
    id: "374",
    district_id: "47",
    name: "Tongibari",
    bn_name: "টংগীবাড়ি",
    zip_code: "1550",
  },
  {
    id: "375",
    district_id: "48",
    name: "Rajbari Sadar",
    bn_name: "রাজবাড়ী সদর",
    zip_code: "7700",
  },
  {
    id: "376",
    district_id: "48",
    name: "Goalanda",
    bn_name: "গোয়ালন্দ",
    zip_code: "7730",
  },
  {
    id: "377",
    district_id: "48",
    name: "Pangsa",
    bn_name: "পাংশা",
    zip_code: "7750",
  },
  {
    id: "378",
    district_id: "48",
    name: "Baliakandi",
    bn_name: "বালিয়াকান্দি",
    zip_code: "7710",
  },
  {
    id: "379",
    district_id: "48",
    name: "Kalukhali",
    bn_name: "কালুখালী",
    zip_code: "7720",
  },
  {
    id: "380",
    district_id: "49",
    name: "Madaripur Sadar",
    bn_name: "মাদারীপুর সদর",
    zip_code: "7900",
  },
  {
    id: "381",
    district_id: "49",
    name: "Shibchar",
    bn_name: "শিবচর",
    zip_code: "7920",
  },
  {
    id: "382",
    district_id: "49",
    name: "Kalkini",
    bn_name: "কালকিনি",
    zip_code: "7910",
  },
  {
    id: "383",
    district_id: "49",
    name: "Rajoir",
    bn_name: "রাজৈর",
    zip_code: "7930",
  },
  {
    id: "384",
    district_id: "50",
    name: "Gopalganj Sadar",
    bn_name: "গোপালগঞ্জ সদর",
    zip_code: "8100",
  },
  {
    id: "385",
    district_id: "50",
    name: "Kashiani",
    bn_name: "কাশিয়ানী",
    zip_code: "8130",
  },
  {
    id: "386",
    district_id: "50",
    name: "Tungipara",
    bn_name: "টুংগীপাড়া",
    zip_code: "8150",
  },
  {
    id: "387",
    district_id: "50",
    name: "Kotalipara",
    bn_name: "কোটালীপাড়া",
    zip_code: "8120",
  },
  {
    id: "388",
    district_id: "50",
    name: "Muksudpur",
    bn_name: "মুকসুদপুর",
    zip_code: "8140",
  },
  {
    id: "389",
    district_id: "51",
    name: "Faridpur Sadar",
    bn_name: "ফরিদপুর সদর",
    zip_code: "7800",
  },
  {
    id: "390",
    district_id: "51",
    name: "Alfadanga",
    bn_name: "আলফাডাঙ্গা",
    zip_code: "7870",
  },
  {
    id: "391",
    district_id: "51",
    name: "Boalmari",
    bn_name: "বোয়ালমারী",
    zip_code: "7820",
  },
  {
    id: "392",
    district_id: "51",
    name: "Sadarpur",
    bn_name: "সদরপুর",
    zip_code: "7840",
  },
  {
    id: "393",
    district_id: "51",
    name: "Nagarkanda",
    bn_name: "নগরকান্দা",
    zip_code: "7850",
  },
  {
    id: "394",
    district_id: "51",
    name: "Bhanga",
    bn_name: "ভাঙ্গা",
    zip_code: "7810",
  },
  {
    id: "395",
    district_id: "51",
    name: "Charbhadrasan",
    bn_name: "চরভদ্রাসন",
    zip_code: "7830",
  },
  {
    id: "396",
    district_id: "51",
    name: "Madhukhali",
    bn_name: "মধুখালী",
    zip_code: "7890",
  },
  {
    id: "397",
    district_id: "51",
    name: "Saltha",
    bn_name: "সালথা",
    zip_code: "7860",
  },
  {
    id: "398",
    district_id: "52",
    name: "Panchagarh Sadar",
    bn_name: "পঞ্চগড় সদর",
    zip_code: "5000",
  },
  {
    id: "399",
    district_id: "52",
    name: "Debiganj",
    bn_name: "দেবীগঞ্জ",
    zip_code: "5020",
  },
  {
    id: "400",
    district_id: "52",
    name: "Boda",
    bn_name: "বোদা",
    zip_code: "5010",
  },
  {
    id: "401",
    district_id: "52",
    name: "Atwari",
    bn_name: "আটোয়ারী",
    zip_code: "5040",
  },
  {
    id: "402",
    district_id: "52",
    name: "Tetulia",
    bn_name: "তেতুলিয়া",
    zip_code: "5030",
  },
  {
    id: "403",
    district_id: "53",
    name: "Nawabganj",
    bn_name: "নবাবগঞ্জ",
    zip_code: "5210",
  },
  {
    id: "404",
    district_id: "53",
    name: "Birganj",
    bn_name: "বীরগঞ্জ",
    zip_code: "5280",
  },
  {
    id: "405",
    district_id: "53",
    name: "Ghoraghat",
    bn_name: "ঘোড়াঘাট",
    zip_code: "5230",
  },
  {
    id: "406",
    district_id: "53",
    name: "Birampur",
    bn_name: "বিরামপুর",
    zip_code: "5270",
  },
  {
    id: "407",
    district_id: "53",
    name: "Parbatipur",
    bn_name: "পার্বতীপুর",
    zip_code: "5255",
  },
  {
    id: "408",
    district_id: "53",
    name: "Bochaganj",
    bn_name: "বোচাগঞ্জ",
    zip_code: "5260",
  },
  {
    id: "409",
    district_id: "53",
    name: "Kaharol",
    bn_name: "কাহারোল",
    zip_code: "5220",
  },
  {
    id: "410",
    district_id: "53",
    name: "Fulbari",
    bn_name: "ফুলবাড়ী",
    zip_code: "5250",
  },
  {
    id: "411",
    district_id: "53",
    name: "Dinajpur Sadar",
    bn_name: "দিনাজপুর সদর",
    zip_code: "5200",
  },
  {
    id: "412",
    district_id: "53",
    name: "Hakimpur",
    bn_name: "হাকিমপুর",
    zip_code: "5215",
  },
  {
    id: "413",
    district_id: "53",
    name: "Khansama",
    bn_name: "খানসামা",
    zip_code: "5290",
  },
  {
    id: "414",
    district_id: "53",
    name: "Birol",
    bn_name: "বিরল",
    zip_code: "5250",
  },
  {
    id: "415",
    district_id: "53",
    name: "Chirirbandar",
    bn_name: "চিরিরবন্দর",
    zip_code: "5240",
  },
  {
    id: "416",
    district_id: "54",
    name: "Lalmonirhat Sadar",
    bn_name: "লালমনিরহাট সদর",
    zip_code: "5500",
  },
  {
    id: "417",
    district_id: "54",
    name: "Kaliganj",
    bn_name: "কালীগঞ্জ",
    zip_code: "5520",
  },
  {
    id: "418",
    district_id: "54",
    name: "Hatibandha",
    bn_name: "হাতীবান্ধা",
    zip_code: "5540",
  },
  {
    id: "419",
    district_id: "54",
    name: "Patgram",
    bn_name: "পাটগ্রাম",
    zip_code: "5510",
  },
  {
    id: "420",
    district_id: "54",
    name: "Aditmari",
    bn_name: "আদিতমারী",
    zip_code: "5530",
  },
  {
    id: "421",
    district_id: "55",
    name: "Syedpur",
    bn_name: "সৈয়দপুর",
    zip_code: "5310",
  },
  {
    id: "422",
    district_id: "55",
    name: "Domar",
    bn_name: "ডোমার",
    zip_code: "5340",
  },
  {
    id: "423",
    district_id: "55",
    name: "Dimla",
    bn_name: "ডিমলা",
    zip_code: "5350",
  },
  {
    id: "424",
    district_id: "55",
    name: "Jaldhaka",
    bn_name: "জলঢাকা",
    zip_code: "5320",
  },
  {
    id: "425",
    district_id: "55",
    name: "Kishorganj",
    bn_name: "কিশোরগঞ্জ",
    zip_code: "5330",
  },
  {
    id: "426",
    district_id: "55",
    name: "Nilphamari Sadar",
    bn_name: "নীলফামারী সদর",
    zip_code: "5300",
  },
  {
    id: "427",
    district_id: "56",
    name: "Sadullapur",
    bn_name: "সাদুল্লাপুর",
    zip_code: "5760",
  },
  {
    id: "428",
    district_id: "56",
    name: "Gaibandha Sadar",
    bn_name: "গাইবান্ধা সদর",
    zip_code: "5700",
  },
  {
    id: "429",
    district_id: "56",
    name: "Palashbari",
    bn_name: "পলাশবাড়ী",
    zip_code: "5720",
  },
  {
    id: "430",
    district_id: "56",
    name: "Saghata",
    bn_name: "সাঘাটা",
    zip_code: "5750",
  },
  {
    id: "431",
    district_id: "56",
    name: "Gobindaganj",
    bn_name: "গোবিন্দগঞ্জ",
    zip_code: "5750",
  },
  {
    id: "432",
    district_id: "56",
    name: "Sundarganj",
    bn_name: "সুন্দরগঞ্জ",
    zip_code: "5710",
  },
  {
    id: "433",
    district_id: "56",
    name: "Phulchari",
    bn_name: "ফুলছড়ি",
    zip_code: "5780",
  },
  {
    id: "434",
    district_id: "57",
    name: "Thakurgaon Sadar",
    bn_name: "ঠাকুরগাঁও সদর",
    zip_code: "5100",
  },
  {
    id: "435",
    district_id: "57",
    name: "Pirganj",
    bn_name: "পীরগঞ্জ",
    zip_code: "5130",
  },
  {
    id: "436",
    district_id: "57",
    name: "Ranisankail",
    bn_name: "রাণীশংকৈল",
    zip_code: "5110",
  },
  {
    id: "437",
    district_id: "57",
    name: "Haripur",
    bn_name: "হরিপুর",
    zip_code: "5140",
  },
  {
    id: "438",
    district_id: "57",
    name: "Baliadangi",
    bn_name: "বালিয়াডাঙ্গী",
    zip_code: "5120",
  },
  {
    id: "495",
    district_id: "57",
    name: "Ruhea",
    bn_name: "রুহিয়া",
    zip_code: "5103",
  },
  {
    id: "496",
    district_id: "57",
    name: "Bhulli",
    bn_name: "ভুল্লী",
    zip_code: "5100",
  },
  {
    id: "439",
    district_id: "58",
    name: "Rangpur Sadar",
    bn_name: "রংপুর সদর",
    zip_code: "5400",
  },
  {
    id: "440",
    district_id: "58",
    name: "Gangachara",
    bn_name: "গংগাচড়া",
    zip_code: "5410",
  },
  {
    id: "441",
    district_id: "58",
    name: "Taragonj",
    bn_name: "তারাগঞ্জ",
    zip_code: "5420",
  },
  {
    id: "442",
    district_id: "58",
    name: "Badargonj",
    bn_name: "বদরগঞ্জ",
    zip_code: "5410",
  },
  {
    id: "443",
    district_id: "58",
    name: "Mithapukur",
    bn_name: "মিঠাপুকুর",
    zip_code: "5470",
  },
  {
    id: "444",
    district_id: "58",
    name: "Pirgonj",
    bn_name: "পীরগঞ্জ",
    zip_code: "5490",
  },
  {
    id: "445",
    district_id: "58",
    name: "Kaunia",
    bn_name: "কাউনিয়া",
    zip_code: "5430",
  },
  {
    id: "446",
    district_id: "58",
    name: "Pirgacha",
    bn_name: "পীরগাছা",
    zip_code: "5460",
  },
  {
    id: "447",
    district_id: "59",
    name: "Kurigram Sadar",
    bn_name: "কুড়িগ্রাম সদর",
    zip_code: "5600",
  },
  {
    id: "448",
    district_id: "59",
    name: "Nageshwari",
    bn_name: "নাগেশ্বরী",
    zip_code: "5620",
  },
  {
    id: "449",
    district_id: "59",
    name: "Bhurungamari",
    bn_name: "ভুরুঙ্গামারী",
    zip_code: "5630",
  },
  {
    id: "450",
    district_id: "59",
    name: "Phulbari",
    bn_name: "ফুলবাড়ী",
    zip_code: "5670",
  },
  {
    id: "451",
    district_id: "59",
    name: "Rajarhat",
    bn_name: "রাজারহাট",
    zip_code: "5640",
  },
  {
    id: "452",
    district_id: "59",
    name: "Ulipur",
    bn_name: "উলিপুর",
    zip_code: "5610",
  },
  {
    id: "453",
    district_id: "59",
    name: "Chilmari",
    bn_name: "চিলমারী",
    zip_code: "5660",
  },
  {
    id: "454",
    district_id: "59",
    name: "Rowmari",
    bn_name: "রৌমারী",
    zip_code: "5650",
  },
  {
    id: "455",
    district_id: "59",
    name: "Charrajibpur",
    bn_name: "চর রাজিবপুর",
    zip_code: "5680",
  },
  {
    id: "456",
    district_id: "60",
    name: "Sherpur Sadar",
    bn_name: "শেরপুর সদর",
    zip_code: "2100",
  },
  {
    id: "457",
    district_id: "60",
    name: "Nalitabari",
    bn_name: "নালিতাবাড়ী",
    zip_code: "2130",
  },
  {
    id: "458",
    district_id: "60",
    name: "Sreebordi",
    bn_name: "শ্রীবরদী",
    zip_code: "2150",
  },
  {
    id: "459",
    district_id: "60",
    name: "Nokla",
    bn_name: "নকলা",
    zip_code: "2140",
  },
  {
    id: "460",
    district_id: "60",
    name: "Jhenaigati",
    bn_name: "ঝিনাইগাতী",
    zip_code: "2120",
  },
  {
    id: "461",
    district_id: "61",
    name: "Fulbaria",
    bn_name: "ফুলবাড়ীয়া",
    zip_code: "2216",
  },
  {
    id: "462",
    district_id: "61",
    name: "Trishal",
    bn_name: "ত্রিশাল",
    zip_code: "2220",
  },
  {
    id: "463",
    district_id: "61",
    name: "Bhaluka",
    bn_name: "ভালুকা",
    zip_code: "2240",
  },
  {
    id: "464",
    district_id: "61",
    name: "Muktagacha",
    bn_name: "মুক্তাগাছা",
    zip_code: "2210",
  },
  {
    id: "465",
    district_id: "61",
    name: "Mymensingh Sadar",
    bn_name: "ময়মনসিংহ সদর",
    zip_code: "2200",
  },
  {
    id: "466",
    district_id: "61",
    name: "Dhobaura",
    bn_name: "ধোবাউড়া",
    zip_code: "2290",
  },
  {
    id: "467",
    district_id: "61",
    name: "Phulpur",
    bn_name: "ফুলপুর",
    zip_code: "2256",
  },
  {
    id: "468",
    district_id: "61",
    name: "Haluaghat",
    bn_name: "হালুয়াঘাট",
    zip_code: "2280",
  },
  {
    id: "469",
    district_id: "61",
    name: "Gouripur",
    bn_name: "গৌরীপুর",
    zip_code: "2270",
  },
  {
    id: "470",
    district_id: "61",
    name: "Gafargaon",
    bn_name: "গফরগাঁও",
    zip_code: "2230",
  },
  {
    id: "471",
    district_id: "61",
    name: "Iswarganj",
    bn_name: "ঈশ্বরগঞ্জ",
    zip_code: "2260",
  },
  {
    id: "472",
    district_id: "61",
    name: "Nandail",
    bn_name: "নান্দাইল",
    zip_code: "2250",
  },
  {
    id: "473",
    district_id: "61",
    name: "Tarakanda",
    bn_name: "তারাকান্দা",
    zip_code: "2296",
  },
  {
    id: "474",
    district_id: "62",
    name: "Jamalpur Sadar",
    bn_name: "জামালপুর সদর",
    zip_code: "2000",
  },
  {
    id: "475",
    district_id: "62",
    name: "Melandah",
    bn_name: "মেলান্দহ",
    zip_code: "2030",
  },
  {
    id: "476",
    district_id: "62",
    name: "Islampur",
    bn_name: "ইসলামপুর",
    zip_code: "2010",
  },
  {
    id: "477",
    district_id: "62",
    name: "Dewangonj",
    bn_name: "দেওয়ানগঞ্জ",
    zip_code: "2020",
  },
  {
    id: "478",
    district_id: "62",
    name: "Sarishabari",
    bn_name: "সরিষাবাড়ী",
    zip_code: "2050",
  },
  {
    id: "479",
    district_id: "62",
    name: "Madarganj",
    bn_name: "মাদারগঞ্জ",
    zip_code: "2040",
  },
  {
    id: "480",
    district_id: "62",
    name: "Bokshiganj",
    bn_name: "বকশীগঞ্জ",
    zip_code: "2080",
  },
  {
    id: "481",
    district_id: "63",
    name: "Barhatta",
    bn_name: "বারহাট্টা",
    zip_code: "2440",
  },
  {
    id: "482",
    district_id: "63",
    name: "Durgapur",
    bn_name: "দুর্গাপুর",
    zip_code: "2420",
  },
  {
    id: "483",
    district_id: "63",
    name: "Kendua",
    bn_name: "কেন্দুয়া",
    zip_code: "2410",
  },
  {
    id: "484",
    district_id: "63",
    name: "Atpara",
    bn_name: "আটপাড়া",
    zip_code: "2470",
  },
  {
    id: "485",
    district_id: "63",
    name: "Madan",
    bn_name: "মদন",
    zip_code: "2460",
  },
  {
    id: "486",
    district_id: "63",
    name: "Khaliajuri",
    bn_name: "খালিয়াজুরী",
    zip_code: "2480",
  },
  {
    id: "487",
    district_id: "63",
    name: "Kalmakanda",
    bn_name: "কলমাকান্দা",
    zip_code: "2450",
  },
  {
    id: "488",
    district_id: "63",
    name: "Mohongonj",
    bn_name: "মোহনগঞ্জ",
    zip_code: "2430",
  },
  {
    id: "489",
    district_id: "63",
    name: "Purbadhala",
    bn_name: "পূর্বধলা",
    zip_code: "2490",
  },
  {
    id: "490",
    district_id: "63",
    name: "Netrokona Sadar",
    bn_name: "নেত্রকোণা সদর",
    zip_code: "2400",
  },
  {
    id: "491",
    district_id: "8",
    name: "Eidgaon",
    bn_name: "ঈদগাঁও",
    zip_code: "4703",
  },
  {
    id: "492",
    district_id: "38",
    name: "Madhyanagar",
    bn_name: "মধ্যনগর",
    zip_code: "3085",
  },
  {
    id: "493",
    district_id: "49",
    name: "Dasar",
    bn_name: "ডাসার",
    zip_code: "7940",
  },
  {
    id: "494",
    district_id: "46",
    name: "Dhaka Sadar",
    bn_name: "ঢাকা সদর",
    zip_code: "1000",
  },
  // Dhaka City Thanas
  {
    id: "501",
    district_id: "46",
    name: "Adabar",
    bn_name: "আদাবর",
    zip_code: "1207",
  },
  {
    id: "502",
    district_id: "46",
    name: "Badda",
    bn_name: "বাড্ডা",
    zip_code: "1212",
  },
  {
    id: "503",
    district_id: "46",
    name: "Bangsal",
    bn_name: "বংশাল",
    zip_code: "1100",
  },
  {
    id: "504",
    district_id: "46",
    name: "Bhashantek",
    bn_name: "ভাষানটেক",
    zip_code: "1206",
  },
  {
    id: "505",
    district_id: "46",
    name: "Cantonment",
    bn_name: "ক্যান্টনমেন্ট",
    zip_code: "1206",
  },
  {
    id: "506",
    district_id: "46",
    name: "Chawkbazar",
    bn_name: "চকবাজার",
    zip_code: "1211",
  },
  {
    id: "507",
    district_id: "46",
    name: "Darus Salam",
    bn_name: "দারুস সালাম",
    zip_code: "1216",
  },
  {
    id: "508",
    district_id: "46",
    name: "Demra",
    bn_name: "ডেমরা",
    zip_code: "1360",
  },
  {
    id: "509",
    district_id: "46",
    name: "Dhanmondi",
    bn_name: "ধানমন্ডি",
    zip_code: "1205",
  },
  {
    id: "510",
    district_id: "46",
    name: "Gendaria",
    bn_name: "গেন্ডারিয়া",
    zip_code: "1204",
  },
  {
    id: "511",
    district_id: "46",
    name: "Gulshan",
    bn_name: "গুলশান",
    zip_code: "1212",
  },
  {
    id: "512",
    district_id: "46",
    name: "Hatirjheel",
    bn_name: "হাতিরঝিল",
    zip_code: "1219",
  },
  {
    id: "513",
    district_id: "46",
    name: "Hazaribagh",
    bn_name: "হাজারীবাগ",
    zip_code: "1209",
  },
  {
    id: "514",
    district_id: "46",
    name: "Jatrabari",
    bn_name: "যাত্রাবাড়ী",
    zip_code: "1236",
  },
  {
    id: "515",
    district_id: "46",
    name: "Kadamtali",
    bn_name: "কদমতলী",
    zip_code: "1236",
  },
  {
    id: "516",
    district_id: "46",
    name: "Kafrul",
    bn_name: "কাফরুল",
    zip_code: "1206",
  },
  {
    id: "517",
    district_id: "46",
    name: "Kalabagan",
    bn_name: "কলাবাগান",
    zip_code: "1205",
  },
  {
    id: "518",
    district_id: "46",
    name: "Kamrangirchar",
    bn_name: "কামরাঙ্গীরচর",
    zip_code: "1211",
  },
  {
    id: "519",
    district_id: "46",
    name: "Khilgaon",
    bn_name: "খিলগাঁও",
    zip_code: "1219",
  },
  {
    id: "520",
    district_id: "46",
    name: "Khilkhet",
    bn_name: "খিলক্ষেত",
    zip_code: "1229",
  },
  {
    id: "521",
    district_id: "46",
    name: "Kotwali",
    bn_name: "কোতয়ালী",
    zip_code: "1100",
  },
  {
    id: "522",
    district_id: "46",
    name: "Lalbagh",
    bn_name: "লালবাগ",
    zip_code: "1211",
  },
  {
    id: "523",
    district_id: "46",
    name: "Mirpur",
    bn_name: "মিরপুর",
    zip_code: "1216",
  },
  {
    id: "524",
    district_id: "46",
    name: "Mohammadpur",
    bn_name: "মোহাম্মদপুর",
    zip_code: "1207",
  },
  {
    id: "525",
    district_id: "46",
    name: "Motijheel",
    bn_name: "মতিঝিল",
    zip_code: "1000",
  },
  {
    id: "526",
    district_id: "46",
    name: "Mugda",
    bn_name: "মুগদা",
    zip_code: "1214",
  },
  {
    id: "527",
    district_id: "46",
    name: "New Market",
    bn_name: "নিউ মার্কেট",
    zip_code: "1205",
  },
  {
    id: "528",
    district_id: "46",
    name: "Pallabi",
    bn_name: "পল্লবী",
    zip_code: "1216",
  },
  {
    id: "529",
    district_id: "46",
    name: "Paltan",
    bn_name: "পল্টন",
    zip_code: "1000",
  },
  {
    id: "530",
    district_id: "46",
    name: "Ramna",
    bn_name: "রমনা",
    zip_code: "1000",
  },
  {
    id: "531",
    district_id: "46",
    name: "Rampura",
    bn_name: "রামপুরা",
    zip_code: "1219",
  },
  {
    id: "532",
    district_id: "46",
    name: "Sabujbagh",
    bn_name: "সবুজবাগ",
    zip_code: "1214",
  },
  {
    id: "533",
    district_id: "46",
    name: "Shah Ali",
    bn_name: "শাহ আলী",
    zip_code: "1216",
  },
  {
    id: "534",
    district_id: "46",
    name: "Shahbag",
    bn_name: "শাহবাগ",
    zip_code: "1000",
  },
  {
    id: "535",
    district_id: "46",
    name: "Shahjahanpur",
    bn_name: "শাহজাহানপুর",
    zip_code: "1217",
  },
  {
    id: "536",
    district_id: "46",
    name: "Sher-e-Bangla Nagar",
    bn_name: "শেরেবাংলা নগর",
    zip_code: "1207",
  },
  {
    id: "537",
    district_id: "46",
    name: "Shyampur",
    bn_name: "শ্যামপুর",
    zip_code: "1204",
  },
  {
    id: "538",
    district_id: "46",
    name: "Sutrapur",
    bn_name: "সূত্রাপুর",
    zip_code: "1100",
  },
  {
    id: "539",
    district_id: "46",
    name: "Tejgaon",
    bn_name: "তেজগাঁও",
    zip_code: "1215",
  },
  {
    id: "540",
    district_id: "46",
    name: "Turag",
    bn_name: "তুরাগ",
    zip_code: "1230",
  },
  {
    id: "541",
    district_id: "46",
    name: "Uttara East",
    bn_name: "উত্তরা পূর্ব",
    zip_code: "1230",
  },
  {
    id: "542",
    district_id: "46",
    name: "Uttara West",
    bn_name: "উত্তরা পশ্চিম",
    zip_code: "1230",
  },
  {
    id: "543",
    district_id: "46",
    name: "Uttarkhan",
    bn_name: "উত্তরখান",
    zip_code: "1230",
  },
  {
    id: "544",
    district_id: "46",
    name: "Vatara",
    bn_name: "ভাটারা",
    zip_code: "1212",
  },
  {
    id: "545",
    district_id: "46",
    name: "Wari",
    bn_name: "ওয়ারী",
    zip_code: "1203",
  },

  // Chattogram City Thanas
  {
    id: "601",
    district_id: "7",
    name: "Akbarshah",
    bn_name: "আকবরশাহ",
    zip_code: "4207",
  },
  {
    id: "602",
    district_id: "7",
    name: "Bakalia",
    bn_name: "বাকলিয়া",
    zip_code: "4203",
  },
  {
    id: "603",
    district_id: "7",
    name: "Bandar",
    bn_name: "বন্দর",
    zip_code: "4100",
  },
  {
    id: "604",
    district_id: "7",
    name: "Bayazid",
    bn_name: "বায়েজিদ",
    zip_code: "4210",
  },
  {
    id: "605",
    district_id: "7",
    name: "Chandgaon",
    bn_name: "চান্দগাঁও",
    zip_code: "4212",
  },
  {
    id: "606",
    district_id: "7",
    name: "Double Mooring",
    bn_name: "ডবলমুরিং",
    zip_code: "4100",
  },
  {
    id: "607",
    district_id: "7",
    name: "EPZ",
    bn_name: "ইপিজেড",
    zip_code: "4222",
  },
  {
    id: "608",
    district_id: "7",
    name: "Halishahar",
    bn_name: "হালিশহর",
    zip_code: "4216",
  },
  {
    id: "609",
    district_id: "7",
    name: "Khulshi",
    bn_name: "খুলশী",
    zip_code: "4225",
  },
  {
    id: "610",
    district_id: "7",
    name: "Kotwali",
    bn_name: "কোতয়ালী",
    zip_code: "4000",
  },
  {
    id: "611",
    district_id: "7",
    name: "Pahartali",
    bn_name: "পাহাড়তলী",
    zip_code: "4202",
  },
  {
    id: "612",
    district_id: "7",
    name: "Panchlaish",
    bn_name: "পাঁচলাইশ",
    zip_code: "4203",
  },
  {
    id: "613",
    district_id: "7",
    name: "Patenga",
    bn_name: "পতেঙ্গা",
    zip_code: "4204",
  },

  // Rajshahi City Thanas
  {
    id: "701",
    district_id: "14",
    name: "Boalia",
    bn_name: "বোয়ালিয়া",
    zip_code: "6100",
  },
  {
    id: "702",
    district_id: "14",
    name: "Matihar",
    bn_name: "মতিহার",
    zip_code: "6206",
  },
  {
    id: "703",
    district_id: "14",
    name: "Rajpara",
    bn_name: "রাজপাড়া",
    zip_code: "6000",
  },
  {
    id: "704",
    district_id: "14",
    name: "Shah Makhdum",
    bn_name: "শাহ মখদুম",
    zip_code: "6207",
  },

  // Khulna City Thanas
  {
    id: "801",
    district_id: "26",
    name: "Daulatpur",
    bn_name: "দৌলতপুর",
    zip_code: "9202",
  },
  {
    id: "802",
    district_id: "26",
    name: "Khalishpur",
    bn_name: "খালিশপুর",
    zip_code: "9000",
  },
  {
    id: "803",
    district_id: "26",
    name: "Khan Jahan Ali",
    bn_name: "খান জাহান আলী",
    zip_code: "9203",
  },
  {
    id: "804",
    district_id: "26",
    name: "Kotwali",
    bn_name: "কোতয়ালী",
    zip_code: "9100",
  },
  {
    id: "805",
    district_id: "26",
    name: "Sonadanga",
    bn_name: "সোনাডাঙ্গা",
    zip_code: "9100",
  },

  // Sylhet City Thanas
  {
    id: "901",
    district_id: "35",
    name: "Airport",
    bn_name: "এয়ারপোর্ট",
    zip_code: "3100",
  },
  {
    id: "902",
    district_id: "35",
    name: "Kotwali",
    bn_name: "কোতয়ালী",
    zip_code: "3100",
  },
  {
    id: "903",
    district_id: "35",
    name: "Jalalabad",
    bn_name: "জালালাবাদ",
    zip_code: "3100",
  },
  {
    id: "904",
    district_id: "35",
    name: "Mogla Bazar",
    bn_name: "মোগলা বাজার",
    zip_code: "3100",
  },
  {
    id: "905",
    district_id: "35",
    name: "Shah Poran",
    bn_name: "শাহ পরান",
    zip_code: "3100",
  },
  {
    id: "906",
    district_id: "35",
    name: "South Surma",
    bn_name: "দক্ষিণ সুরমা",
    zip_code: "3100",
  },
];

export default upazilas;
